enum {
	GDT_KERNEL_CODE = 1,
	GDT_KERNEL_DATA = 2,
	GDT_USER_CODE = 3,
	GDT_USER_DATA = 4,
};

enum {
	SEG_KERNEL_CODE = GDT_KERNEL_CODE * 8,
	SEG_KERNEL_DATA = GDT_KERNEL_DATA * 8,
	SEG_USER_CODE = GDT_USER_CODE * 8,
	SEG_USER_DATA = GDT_USER_DATA * 8,
};
